on: push
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v2
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          USERNAME: "op://4znpwcqkyydycs7wvm7kg3a3ri/test login item/username"
          PASSWORD: "op://4znpwcqkyydycs7wvm7kg3a3ri/test login item/password"

      - name: Print masked secret
        run: 'echo "USERNAME: ${{ steps.op-load-secret.outputs.USERNAME }}"
              echo "PASSWORD: ${{ steps.op-load-secret.outputs.PASSWORD }}"'
        # Prints: Secret: ***