on: push
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Load secret
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_CONNECT_HOST: http://159.203.49.65:8080
          OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
          USERNAME: "op://vznh73vmml3xake4byghvbydda/bs test item/username"
          PASSWORD: "op://vznh73vmml3xake4byghvbydda/bs test item/password"

      - name: Print masked secret
        run: 'echo "Username: $USERNAME"
              echo "Password: $USERNAME"'
        # Prints: Secret: ***