on: push

permissions:
  id-token: write
  contents: read

jobs:
  my-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Load secrets from 1Password
        uses: 1Password/load-secrets-action@v5beta
        env:
          OP_WORKLOAD_ID: "UFDGO7HTQ5A4TOTSUVPZ7F3VVM"
          OP_ENVIRONMENT_ID: "zaunjvlsva6tlpk7xbrseefyte"
          OP_INTEGRATION_KEY: ${{ secrets.OP_INTEGRATION_KEY }}

      - name: Print masked secret
        run: |
          echo "Username"
          echo "Password"