name: 1Password
on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: install 1password
        run: brew install --cask 1password/tap/1password-cli

      - name: start op
        run: | 
          op --version
          op account add --address my.b5test.com --email nhat.nguyen@agilebits.com --secret-key A3-VG7W87-DSZXDB-XX2EF-GMGQ9-QJLZQ-LDE2G
