name: Test 1Password CLI Installation

on: push

jobs:
  install-1pw-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run test.js to install 1Password CLI
        run: node test.js

      - name: Check "op --version"
        run: echo $(op --version)
      
      - name: test js file
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        run: |
          op vault ls
          op item ls --vault "mfsqhaf3zntu2mgjzaqpdedkba"

