name: 1Password
on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: install 1password
        run: brew install --cask 1password/tap/1password-cli

      - name: start op
        run: | 
          op --version
          export OP_SECRET_KEY="A3-7QB89A-RQY3J9-8N4Y7-Y7PC7-V43MK-B5C7T"
          op account add --address my.1password.com --email emailforwork111222@gmail.com
          eval $(echo "04081984kimnhat" | op signin)
        
