name: 1Password
on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLI_VERSION: 1password-cli-amd64-latest.deb
      URL: ${{secrets.URL}}
      EMAIL: ${{secrets.EMAIL}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      PASSWORD: ${{secrets.PASSWORD}}
      ADDRESS: my.b5test.com

    steps:
      - uses: actions/checkout@v3
      - name: install 1password
        run: |
          wget https://downloads.1password.com/linux/debian/amd64/stable/$CLI_VERSION
          sudo dpkg --force-confold -i $CLI_VERSION
          op --version
        
      - name: run from script
        run: |
          chmod +x ./op.sh
          ./op.sh
          echo "script run successfully"
        shell: bash
          
