# This is a basic workflow to help you get started with Actions

name: 1Password
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest

    steps:

      - name: Get 1Password device ID from macOS runner shell
        shell: /bin/bash -l {0}
        run: |
          head -c 16 /dev/urandom | base32 | tr -d = | tr '[:upper:]' '[:lower:]'
          echo "OP_DEVICE=$OP_DEVICE" >> $GITHUB_ENV
          echo "::add-mask::$OP_DEVICE"

      - name: Import Secrets
        uses: RobotsAndPencils/1password-action@v1
        id: secrets
        with:
          device-id: ${{ secrets.OP_DEVICE_ID }}
          sign-in-address: ${{ secrets.OP_SIGN_IN_ADDRESS }}
          email-address: ${{ secrets.OP_EMAIL_ADDRESS }}
          secret-key: ${{ secrets.OP_SECRET_KEY }}
          master-password: ${{ secrets.OP_MASTER_PASSWORD }}
          items: |
            Client A > App Store Connect
            Client A > Certificate | p12
            Client A > Provisioning Profile
      
      - name: test op
        run: op --version
