name: 1Password
on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLI_VERSION: 1password-cli-amd64-latest.deb
      URL: ${{secrets.URL}}
      EMAIL: ${{secrets.EMAIL}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      PASSWORD: ${{secrets.PASSWORD}}
      ADDRESS: my.b5test.com

    steps:
      - uses: actions/checkout@v3
      - name: install 1password
        run: |
          wget https://downloads.1password.com/linux/debian/amd64/stable/$CLI_VERSION
          sudo dpkg --force-confold -i $CLI_VERSION
          op --version
        
      - name: start op
        run: | 
          eval $(echo "$PASSWORD" | op account add --address $ADDRESS --email $EMAIL --secret-key $SECRET_KEY --signin)
          op vault list
          op item create --category ssh --title "github actions key 2" --ssh-generate-key "RSA" --vault "vznh73vmml3xake4byghvbydda"
