# This is a basic workflow to help you get started with Actions

name: 1Password
on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: install 1password
        run: |
          sodo brew cask upgrade
          sudo brew install --cask 1password/tap/1password-cli,
      
      - name: begin working with 1pw CLI
        run: | 
          op --version
        
        
