# GitHub Actions yaml
name: Build
on:
  push:
    branches: [ "main" ]
jobs:
  dev-build:
    runs-on: ubuntu-latest
    env:
      CLI_VERSION: 1password-cli-amd64-latest.deb
      #OP_CONNECT_HOST: http://localhost:8080
      # OP_CONNECT_HOST: http://24.144.69.128:8080
      # OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
      # TEST_VAR: "op://testing_2/test bs item/username"
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      SECRET: op read "op://testing_2/SSH Key/private key?ssh-format=openssh"
    steps:
      - name: use 1password load secret or CLI.
        run: |
          wget https://downloads.1password.com/linux/debian/amd64/stable/$CLI_VERSION
          sudo dpkg --force-confold -i $CLI_VERSION
          op --version
        # uses: 1password/load-secrets-action@v1
      - uses: actions/checkout@v3 #checkout@v2 is no longer supported
      - name: Run script
        run: |
          export OP_SERVICE_ACCOUNT_TOKEN=$OP_SERVICE_ACCOUNT_TOKEN
          echo $SECRET
        # run: |
        #   echo $TEST_VAR
